#!/bin/sh

CPSTL_SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
CPSTL_ROOT=$(CDPATH= cd -- "$CPSTL_SCRIPT_DIR/.." && pwd)
CPSTL_BUILD_ROOT="$CPSTL_ROOT/build"
CPSTL_DIST_ROOT="$CPSTL_ROOT/dist"
CPSTL_ROMODULAR_SCRIPTS="$CPSTL_ROOT/tools/RoModularBuild/scripts"

if [ ! -f "$CPSTL_ROMODULAR_SCRIPTS/common.sh" ]; then
    printf '%s\n' \
        "error: RoModularBuild is unavailable; initialize tools/RoModularBuild with git submodule update --init --recursive" \
        >&2
    exit 2
fi

ROMODULAR_PROJECT_ROOT=$CPSTL_ROOT
ROMODULAR_BUILD_ROOT=$CPSTL_BUILD_ROOT
ROMODULAR_DIST_ROOT=$CPSTL_DIST_ROOT
ROMODULAR_PROJECT_LABEL=CPSTL
ROMODULAR_CONFIGURE_COMMAND=scripts/configure.sh
ROMODULAR_DEFAULT_CONFIGURATION=Debug
ROMODULAR_INSTALL_CONFIGURATION=Release
ROMODULAR_TESTING_CACHE_ARGUMENT=-DCPSTL_TESTING=ON
ROMODULAR_EXAMPLES_CACHE_ARGUMENT=-DCPSTL_EXAMPLES=ON

export \
    ROMODULAR_PROJECT_ROOT \
    ROMODULAR_BUILD_ROOT \
    ROMODULAR_DIST_ROOT \
    ROMODULAR_PROJECT_LABEL \
    ROMODULAR_CONFIGURE_COMMAND \
    ROMODULAR_DEFAULT_CONFIGURATION \
    ROMODULAR_INSTALL_CONFIGURATION \
    ROMODULAR_TESTING_CACHE_ARGUMENT \
    ROMODULAR_EXAMPLES_CACHE_ARGUMENT
